name: ci Pipeline

#permission minimale , utiles en version prod , mais c'est mon projet    alors je me priverais pas de mes propres droits
#permissions:
  #contents: read


#trigger
on:
  push:
   branches: [master]

  pull_request:
   branches: [master]

#les actions 

jobs: 
  test:
   runs-on